test suites for gitbase + bblfshd(mocked up)
src-d/regression-gitbase pull request #22
Opened 2019-08-14 16:24 UTC by lwsanty

This is a suite that checks if gitbase correctly handles the difficulties that may appear during the interaction with bblfshd GRPC server, such as parse request errors, parse errors, broken UASTs, long parse time evaluation etc.

It uses different bblfshd mockups to be served, regression-core to spin up the gitbase and perform queries.

To assert gitbase behavior it's stderr is being parsed after the query execution.

This tests are been compiled to a simple binary that's added to regression gitbase docker and should be launched during the gitbase regression test routine.

closes #18

Signed-off-by: lwsanty <lwsanty@gmail.com>

2019-08-14 16:26 UTC, lwsanty commented
this pr is blocked by https://github.com/src-d/gitbase/issues/950

2019-08-15 08:10 UTC, jfontan commented
Maybe I understand the changes incorrectly but these tests seem like integration tests and I feel they belong to gitbase repo instead of regression.

2019-08-15 15:59 UTC, lwsanty commented
@jfontan I did it here taking into account such things:
1) `regression-gitbase` already has a toolkit for preparation of server, repos etc
2) it takes ~30 seconds for this suite to pass, I did not want to include this heavy staff to `gitbase` repo and test it per commit or so I think this suite would fit better in a regression suite
3) I don't need to know the internals of `gitbase` so it's enough for me just to use it's binary here

Anyways I don't insist on storing these tests here, but in `gitbase` case it will take time to: 
1) rewrite the suite to standard golang tests form
2) implement preparations in `gitbase` that are already provided in `regression-gitbase`

2019-08-19 08:26 UTC, ajnavarro requested changes

2019-08-19 08:26 UTC, ajnavarro commented on bblfsh-mockups/services.go
> +	return &v2.ParseResponse{Language: "go", Uast: buf.Bytes(), Errors: []*v2.ParseError{{"wowwowwow"}}}, nil
Leftover?

2019-08-19 08:26 UTC, ajnavarro commented on capture-output/capture_output.go
> +	fmt.Println("data:", string(data))
leftover?

2019-08-19 09:01 UTC, erizocosmico approved these changes
LGTM

2019-08-19 09:53 UTC, lwsanty commented on bblfsh-mockups/services.go
> +	return &v2.ParseResponse{Language: "go", Uast: buf.Bytes(), Errors: []*v2.ParseError{{"wowwowwow"}}}, nil
Done.

2019-08-19 09:53 UTC, lwsanty commented on capture-output/capture_output.go
> +	fmt.Println("data:", string(data))
Done.

2019-08-19 10:50 UTC, jfontan approved these changes

2019-08-19 13:09 UTC, ajnavarro approved these changes

2019-08-19 13:09 UTC, merged